app/urls.py
# -*- coding: utf-8 -*-
# WEBSITE
import js_translations.views
import home.admin

# ATUIN
import atuin.js_translations.views
import atuin.auth.views
import atuin.auth.admin

# ATUIN CMS
import atuincms.js_translations.views
import atuincms.auth.views
import atuincms.home.admin
import atuincms.media.admin
import atuincms.menus.admin
import atuincms.sections.admin
import atuincms.pages.admin
import atuincms.sitemap_robots.views
import atuincms.router.handler

mounts = [
    # WEBSITE
    ('/', js_translations.views),
    ('/', home.admin),

    # ATUIN
    ('/', atuin.js_translations.views),
    ('/', atuin.auth.views),
    ('/', atuin.auth.admin),

    # ATUIN CMS
    ('/', atuincms.js_translations.views),
    ('/', atuincms.auth.views),
    ('/', atuincms.home.admin),
    ('/', atuincms.media.admin),
    ('/', atuincms.menus.admin),
    ('/', atuincms.sections.admin),
    ('/', atuincms.pages.admin),
    ('/', atuincms.sitemap_robots.views),

    ('/', atuincms.router.handler),
]

app/js_translations/views.py
# -*- coding: utf-8 -*-
import time
from flask.blueprints import Blueprint
from flask import render_template, make_response

bp = Blueprint('js_translations', __name__)


@bp.route(u'en/js_translations.js', endpoint='index_en')
@bp.route(u'js_translations.js')
def index():
    resp = make_response(render_template('js_translations/base.js'))
    resp.headers['Content-Type'] = 'application/javascript'
    resp.cache_control.max_age = 60 * 60
    resp.expires = int(time.time() + 60 * 60)

    return resp

app/templates/template/base.html
{% extends 'atuincms/pages/base.html' %}
{%- block atuincms_page_html_class -%}page {{ page.p_template_id }}{%- endblock -%}
{%- block atuincms_page_title -%}{{ page.name }}{%- endblock -%}

{# CSS #}
{% block atuincms_css_imports %}
	<!-- My custom base template CSS imports -->
{% endblock %}
{% block atuincms_css %}
	<link href="/static/min/css/style.css?v={{ SITE_VERSION }}" rel="stylesheet">
	{% block pages_css %}{% endblock %}
{% endblock %}

{% block atuin_metadescription -%}{{ page.description }}{%- endblock %}

{% block atuincms_head_end %}
	<!-- My custom base template head end imports -->

	<!--<script async src="https://www.googletagmanager.com/gtag/js?id=UA-47276148-9"></script>-->
	<!--<script>-->
	  <!--window.dataLayer = window.dataLayer || [];-->
	  <!--function gtag(){dataLayer.push(arguments);}-->
	  <!--gtag('js', new Date());-->

	  <!--gtag('config', '<code>');-->
	<!--</script>-->

	{% block pages_head_end %}{% endblock %}
{% endblock %}


{% block atuincms_pagecontent -%}
	<!-- Website navbar -->
	{% block pagebody %}{% endblock %}
	<!-- Website footer section -->
{%- endblock %}

{# JS #}
{% block atuincms_js_imports %}
	<!-- My custom base template JS imports -->
	{% block pages_js_imports %}{% endblock %}
{% endblock %}
{% block atuincms_js %}
	<script src="{{ lurl_for('js_translations.index', v=SITE_VERSION) }}"></script>
	<script src="/static/min/js/all.js?v={{ SITE_VERSION }}"></script>
	{% block pages_js %}{% endblock %}
{% endblock %}

{% block atuincms_foot_end %}
	<!-- My custom base template footer end imports -->
	{% block pages_foot_end %}{% endblock %}
{% endblock %}

app/templates/template/base_img_header.html
{% extends 'template/base.html' %}
{%- block atuincms_page_html_class -%}page {{ page.p_template_id }}{%- endblock -%}
{%- block atuincms_page_title -%}{{ page.name }}{%- endblock -%}

{% block pagebody %}
	<div class="headTitle" style="background-image: url({{ page.collection_image_url('gmt_header', 'image') }})">
		<div class="container">
			<div class="pageTitle">
				{{ page.collection_text('gmt_header', 'title') }}
			</div>
			<div class="pageBreadcrumb">
				{% for idx in page.gmt_breadcrumb_r %}
					{% set inter_link = '' if loop.first else ' / ' %}
					{% if page.collection_linked_page_exists('gmt_breadcrumb', 'link', idx) %}
						{{ inter_link }}
						<a href="{{ page.collection_linked_page_url('gmt_breadcrumb', 'link', idx) }}">
							{{ page.collection_text('gmt_breadcrumb', 'text', idx) }}
						</a>
					{% endif %}
				{% endfor %}
			</div>
		</div>
	</div>
	{% block pagebody_img_header %}{% endblock %}
{% endblock %}